### ISSUE TITLE
Set Default Selection

### ISSUE THREAD

**Issue by samxi** [immense/immybox#12]
Is there a way to set an option as selected by default instead of showing a placeholder? I did not see this functionality on the demo page

**Comment by thornsereyvong** [comment]
what about defaultSelectValue?

**Comment by thornsereyvong** [comment]
why i set value to property defaultSelectValue it don't have result from it.

**Comment by cbankester** [comment]
Hi @thornsereyvong, you are right, we recently added a new feature to Immybox, `defaultSelectedValue`. Perhaps unexpectedly, it does not actually select a value for you, it simply causes one particular choice to show up first in the list, such that when you open an immybox, that choice is automatically highlighted (it is therefore the default choice for selection).

If you refer to the [demo](http://rawgit.com/immense/immybox/master/demo.html), you will notice that the `defaultSelectedValue` is set to `LA`, causing Louisiana to be at the top of the list.

**Comment by thornsereyvong** [comment]
Hi @cbankester, i want have one choice automatically in text box. You have this function?
