### ISSUE TITLE
Please add a trigger or method to open the list, e.g a link, button etc.

### ISSUE THREAD

**Issue by tno2007** [immense/immybox#21]
Please provide a method or trigger to open the list.

for example:

    $(elm).openList()

or through means of a trigger, for example:

    $(elm).immybox({
        choices: ...
        trigger: "#actionButton"
    })

**Comment by cbankester** [comment]
How about methods like this:
```javascript
$(selector).immybox('open');
$(selector).immybox('close');
```

And if you want to tie a button to opening/closing the immybox, I think it would make more sense to tie the button's click event to a function calling one of those methods above.

**Comment by cmbankester** [comment]
Done, currently sitting in releases/1.0.0 branch
