### ISSUE TITLE
Add css class or attribute to immybox_results div

### ISSUE THREAD

**Issue by tno2007** [immense/immybox#22]
Please add immybox initializations options to add a class or attribute to the results div.

For example:

    $(element).immybox({
	choices: ...,
	cssClass: 'vehicles',
	attribute: {
		name: 'data-vehicles-box'
		value: 'xyz'
	}
});

Will result in this:

    <div class="immybox_results vehicles" data-vehicles-box="xyz">

**Comment by cbankester** [comment]
I don't believe this feature would be very useful. You can always just wrap the immybox in your own div and style the `immybox_results` selector appropriately.
