### ISSUE TITLE
why on IE not working?

### ISSUE THREAD

**Issue by 3ch3r46** [immense/immybox#28]
Why this autocomplete not working on Internet Explorer.
i get this error:
> Unable to get property 'empty' of undefined or null reference

the error in this code

> this.queryResultArea.empty().append(h)

i think, the `empty()` method is undefined.

i test this with IE 10 on windows 8.
i don't know this error is showing on earliest IE or not.
please fix this error.

**Comment by cmckni3** [comment]
I see an error `Object doesn't support this action` after page load.

[Relevant code](https://github.com/immense/immybox/blob/fefc35e73358f19a292df4688a0e920ab4512606/jquery.immybox.coffee#L327):

```coffeescript
@_element.dispatchEvent new Event('input')
```

Will investigate further and attempt to fix.

Pull requests are welcome.

**Comment by 3ch3r46** [comment]
i has been resolve this error and work on my IE, i don't test on IE earliest.
i will fork now.

**Comment by timotheus0106** [comment]
ehm, i get this error too in ie11..

can you please tell us what you did to fix this error?

**Comment by cmckni3** [comment]
See my comment about a polyfill [here](https://github.com/immense/immybox/pull/29#issuecomment-209518392)

**Comment by cmbankester** [comment]
@cmckni3 Should we perhaps add some documentation on getting immybox running in IE?

**Comment by cmckni3** [comment]
Yeah that would be a good idea.

I think we should add the polyfill to do the demo so it works on IE as well.

**Comment by timotheus0106** [comment]
awesome. with that polyfill immybox works for me in ie11

thanks a lot!

**Comment by cmckni3** [comment]
Glad to help @timotheus0106

**Comment by cmckni3** [comment]
Documentation added and polyfill added to demo.
