### ISSUE TITLE
Hide popup when scroll?

### ISSUE THREAD

**Issue by hukacode** [immense/immybox#39]
Hello,

Can you show me how to hide popup when scroll?

![immybox.png](http://2.pik.vn/20168eedac43-ef99-4926-a423-b718666a4bb3.png)

**Comment by cmckni3** [comment]
#### Hide results during scroll

* Adjust CSS of element that will be scrolled

```
// only vertical scrolling
overflow-y: auto; // OR overflow-y: scroll;
```

In the case of the demo, `main` should have `overflow-y: auto` set.

* Listen for scroll event and call immybox's `hideResults` method

```
// with jQuery
$('main').scroll(function(event) {
  $('#input-1').immybox('hideResults');
});

// without jQuery
var main = document.querySelector('main');
main.addEventListener('scroll', function(event) {
  $('#input-1').immybox('hideResults');
});
```
