### ISSUE TITLE
json and jquery

### ISSUE THREAD

**Issue by fatbob1024** [immense/immybox#40]
Hi there

I'm trying to get immybox to populate choices from an external json file in the following format

https://www.optykrozmus.co.uk/scripts/searchAjax.asp?term=col

the choices i'd like to update depending on the "term" in the query string. The term being updated as the user types into the immybox field. This keeps the options small as its from a huge product list 

Is this possible?

Previously i was using jquery ui autocomplete with the following code 

    $("#miniSearchField").autocomplete({
        minLength: 2,
        source: function(request, response) {
            var term = request.term;
            if (term in cache) {
                response(cache[term]);
                return
            }
            lastXhr = $.getJSON("/Scripts/searchAjax.asp", request, function(data, status, xhr) {
                cache[term] = data;
                if (xhr === lastXhr) {
                    response(data)
                }
            })
        }
    });

**Comment by cmckni3** [comment]
Yes, that's possible. Grab a reference to the element with Immybox bound to it and call [`setChoices`](https://github.com/immense/immybox/blob/master/jquery.immybox.coffee#L383).

```
$('#input-1').immybox('setChoices', [{text: 'foo', value: 'foo'}])
```
