### ISSUE TITLE
knockout

### ISSUE THREAD

**Issue by kennarionwong** [immense/immybox#41]
I am trying to implement knockout to handle the value.  Can you provide some samples?  Thanks!

**Comment by cmckni3** [comment]
You can use the ko bindings ([CoffeeScript](https://github.com/immense/immybox/blob/master/knockout-immybox.coffee) [JavaScript](https://github.com/immense/immybox/blob/master/knockout-immybox.min.js) included in the project.

Here's a rough idea of how to use Immybox with knockout.js:
```
// JavaScript
var StateViewModel = function() {
    this.states = [
            {text: 'Alabama', value: 'AL'},
            {text: 'Alaska', value: 'AK'},
            {text: 'Arizona', value: 'AZ'},
            {text: 'Louisiana', value: 'LA'},
    // ...
    ];
    this.selectedState = 'LA';
};
 
ko.applyBindings(new ViewModel());

// html
<input data-bind="immybox_choices: states, immybox_value: selectedState" />
```

[Options](https://github.com/immense/immybox/blob/master/jquery.immybox.js#L10) can be overridden using the `immybox_options`.

Feel free to contribute a PR for the [documentation](http://immybox.js.org/).
