### ISSUE TITLE
Publish 0.5.1 to npm

### ISSUE THREAD

**Issue by cmckni3** [immense/immybox#42]
You ok with this @cmbankester to allow it to be used with npm/yarn or do you think the 1.0.0 betas work well enough?

**Comment by cmckni3** [comment]
Guess I can try out 1.0.0-beta1 since beta 2 and beta 3 aren't published to npmjs.org

**Comment by cmbankester** [comment]
I'll get them all published. Thanks!

**Comment by cmbankester** [comment]
Published 0.5.2, 1.0.0-beta2 and 1.0.0-beta3. Lmk if you have any issues with them
