### ISSUE TITLE
defaultSelectedValue doesn't work

### ISSUE THREAD

**Issue by lloydbanks** [immense/immybox#44]
Not sure if a bug or a feature, but `defaultSelectedValue` refuses to work if you don't specify `value` for input.
Demo of this option is also not working on your website http://immybox.js.org/#options-default-selected-value

**Comment by cmbankester** [comment]
@lloydbanks It seems to be working on the demo. The "defaultSelectedValue" option simply puts that value at the top of the list, such that it is selected (i.e. highlighted) automatically when the user visits the box.
